services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./static:/static:ro
      - ./artwork:/artwork:ro
    restart: unless-stopped
  api:
    container_name: api
    build:
      context: api/docker
      dockerfile: Dockerfile
    command: >
      bash -c "
      python3 manage.py migrate &&
      python3 manage.py createsuperuser_if_none &&
      python3 manage.py create_dummy_users &&
      daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    environment:
      - DJANGO_SUPERUSER_USERNAME=root
      - DJANGO_SUPERUSER_PASSWORD=root
      - DJANGO_SUPERUSER_EMAIL=root@mail.com
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api/backend/:/app:ro
      - ./artwork:/artwork
    restart: unless-stopped
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
