# Generated by Django 5.1 on 2024-11-10 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_message_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='file_path',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='target_player',
        ),
        migrations.AddField(
            model_name='artwork',
            name='available_to',
            field=models.ManyToManyField(blank=True, related_name='available_artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='forced_display',
            field=models.ManyToManyField(blank=True, related_name='forced_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
