# Generated by Django 5.1 on 2024-11-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_remove_artwork_forced_display_playerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initiative', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('is_current_turn', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-initiative', '-dexterity'],
            },
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='forced_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forced_on_profiles', to='dnd.artwork'),
        ),
    ]
